### ISSUE TITLE
Entering Wildfire zone freezes game

### ISSUE THREAD

**Issue by PierreBeucher** [erasels/SpireMapOverhaul#252]
Hello, thanks for this awesome Mod ! :fire: 

I have an issue with Wildfire zone, when entering the zone my game freezes. Nothing obvious appears in logs even with debug enabled. (I can still post them if needed)

A workaround is to disable shaders for Wildfire in Mod's config.

It seems I'm not the only one (eg. https://steamcommunity.com/sharedfiles/filedetails/?id=3142318909 comment 27 May @ 8:33am)

**Comment by erasels** [comment]
A known issue, although I'm unsure if I've pinned down the cause just yet. Can you tell me what OS you're on and what graphics card you have?

**Comment by PierreBeucher** [comment]
I'm using NixOS 23.11 with Raptor Lake-P (Iris Xe Graphics), an integrated GPU (eg. a potato). This happens with and without Proton.

I'm not sure about storm and fog, gonna check

**Comment by PierreBeucher** [comment]
No issue with storm and fog :)

**Comment by erasels** [comment]
Alright, that does strengthen my theory that it's some variables that only work on windows. Thanks for the info, most people dump the log and then never answer back

**Comment by PierreBeucher** [comment]
Haha you're welcome, maintaining a few projects myself I know how frustrating that could be so I don't reproduce the same behavior ;)

**Comment by andrewjsim** [comment]
I play on macOS and the wildfire biome is pitch black, but not frozen, and surprisingly playable if you get lucky with the combats. I've turned off the shader in the settings and it's fine now. When I play on Windows I do get the cool fire effects.

**Comment by erasels** [comment]
Yeah, I've narrowed it down to non-nvidia cards so far, so I'll be making an update that just disables the wildfire shader for that group.

**Comment by erasels** [comment]
9168d436437113a5220a5179da4d12c7f673f091 should fix this
